kedacore/testing-infrastructure

- .terraform.lock.hcl
- modules/azure/aks/main.tf
- terraform.tf
Signed-off-by: Jorge Turrado <jorge.turrado@scrm.lidl>
> feat: use azurerm_federated_identity_credential to federate msi

- .github/workflows/main.yaml
- .github/workflows/pr-validation.yaml
> add login steps

- .terraform.lock.hcl
- main.tf
- modules/gcp/iam/main.tf
- modules/gcp/iam/outputs.tf
- modules/gcp/iam/vars.tf
- terraform.tf
> feat: add GCP IAM module

- modules/gcp/iam/main.tf
> use url encoding for token sub

- modules/gcp/iam/main.tf
> fix: remove sub requirement for IAM federation

- main.tf
- modules/gcp/iam/outputs.tf
> Add GCP envs

- main.tf
- modules/gcp/iam/outputs.tf
> export project number

- modules/gcp/iam/main.tf
> remove aud mapping for gcp

- modules/gcp/iam/main.tf
> fix typo in gcp assignement

- modules/gcp/iam/outputs.tf
> decode sa secret

- main.tf
- modules/azure/event-hub-namespace/main.tf
- modules/azure/event-hub-namespace/vars.tf
- modules/azure/monitor-stack/main.tf
- modules/azure/monitor-stack/vars.tf
- modules/azure/storage-account/main.tf
- modules/azure/storage-account/vars.tf
> azure: add role assignement for managed identities

- modules/azure/data-explorer/main.tf
> fix: Use proper names in azure data explorer role assignements

- modules/azure/aks/main.tf
- modules/azure/data-explorer/main.tf
> add aad-pod-identity role assignements

- main.tf
Related to https://github.com/kedacore/keda/pull/4030
> chore: add full qualified id for msi as secret

- modules/azure/monitor-stack/main.tf
> fix: add missing role assignments

- main.tf
- modules/azure/monitor-stack/outputs.tf
> Add TF_AZURE_APP_INSIGHTS_NAME

- modules/azure/monitor-stack/main.tf
> add az monitor roles

- main.tf
> bump aks version

- modules/azure/monitor-stack/main.tf
> remove not needed role

- modules/azure/monitor-stack/main.tf
> add azure-monitor-workspace

- modules/azure/monitor-stack/main.tf
> change name (#83

- modules/azure/monitor-stack/main.tf
> change name (#84

- main.tf
- modules/azure/aks/main.tf
- modules/azure/aks/vars.tf
- modules/azure/monitor-stack/main.tf
- modules/azure/monitor-stack/outputs.tf
> send AKS metrics to managed prometheus

- modules/azure/aks/main.tf
> fix template

- modules/azure/aks/main.tf
> fix names (#90

- main.tf
- modules/azure/aks/main.tf
- modules/azure/aks/vars.tf
- modules/azure/monitor-stack/main.tf
- modules/azure/monitor-stack/outputs.tf
> add azure managed prometheus rule

- main.tf
- modules/azure/aks/main.tf
- modules/azure/aks/vars.tf
- modules/azure/monitor-stack/main.tf
- modules/azure/monitor-stack/outputs.tf
> deploy prometheus infra

- modules/azure/aks/main.tf
> rename the rules

- modules/azure/monitor-stack/main.tf
Remove `-az` from name as no other Azure resources have references to `Azure`
> chore(azure-monitor): Remove `-az` from name

- modules/azure/monitor-stack/main.tf
- modules/azure/monitor-stack/outputs.tf
> chore: add prometheus endpoint

- modules/azure/aks/main.tf
> chore: Ignore changes in node count

- terraform/vars.tf
> chore: modify unique name

- .github/workflows/main.yaml
- .github/workflows/pr-validation.yaml
- terraform/.terraform.lock.hcl
- terraform/main.tf
- terraform/modules/azure/aks/main.tf
- terraform/modules/azure/aks/vars.tf
- terraform/modules/azure/data-explorer/main.tf
- terraform/modules/azure/event-hub-namespace/main.tf
- terraform/modules/azure/key-vault/main.tf
- terraform/modules/azure/managed_identities/main.tf
- terraform/modules/azure/managed_identities/vars.tf
- terraform/modules/azure/monitor-stack/main.tf
- terraform/modules/azure/service-bus/main.tf
- terraform/modules/azure/service-bus/vars.tf
- terraform/modules/azure/storage-account/main.tf
- terraform/terraform.tf
- terraform/vars.tf
Rename resources to follow the naming convention
Related to #
> chore: rename resources

- terraform/main.tf
- terraform/modules/azure/aks/outputs.tf
> fix: use cluster full names for federations

- terraform/main.tf
> chore: Update terraform with enabled GCP apis

- terraform/main.tf
> chore: bump aks to 1.27

- .github/workflows/main.yaml
- .github/workflows/pr-validation.yaml
- terraform/.terraform.lock.hcl
- terraform/main.tf
- terraform/modules/grafana/iam/main.tf
- terraform/modules/grafana/iam/outputs.tf
- terraform/modules/grafana/iam/vars.tf
- terraform/vars.tf
> feat: manage Grafana Cloud resources

- terraform/main.tf
- terraform/modules/aws/iam/main.tf
- terraform/modules/aws/iam/outputs.tf
> feat: add a second identity for role assumtions

- terraform/modules/aws/iam/main.tf
> Add trusted relations for AWS roles

- terraform/modules/aws/iam/main.tf
> AWS: remove GetQueueAttributes from main role

- terraform/modules/azure/data-explorer/main.tf
> Update Kusto module to remove deprecated field

- terraform/modules/aws/iam/main.tf
> add aws secret manager permission

- terraform/modules/aws/iam/main.tf
> fix: SQS policy doesn't have a type

- terraform/main.tf
- terraform/modules/aws/iam/main.tf
- terraform/modules/aws/iam/outputs.tf
> Add a second workload role for AWS assume role e2e test

- terraform/modules/aws/iam/main.tf
> fix typo in aws iam policy

- terraform/modules/aws/iam/main.tf
> chore: limit aws workload roles to sqs:GetQueueAttributes

- terraform/main.tf
- terraform/modules/aws/iam/main.tf
- terraform/modules/aws/iam/outputs.tf
> chore: Unify AWS WebIdentity trusted relations

- terraform/modules/aws/iam/main.tf
> chore: fix typo on aws iam

- terraform/modules/aws/iam/main.tf
> chore: Add aps permission to role and clean up permissions

- terraform/main.tf
> Upgade AKS to 1.29

- terraform/modules/azure/postgres-flex-server/main.tf
> fix: deploy postgres on NE

- terraform/modules/azure/postgres-flex-server/main.tf
> chore: Rename postgres flex server name

- .github/workflows/main.yaml
- terraform/main.tf
- terraform/modules/azure/aks/main.tf
> Allow AKS preview versions

- terraform/main.tf
- terraform/modules/azure/aks/main.tf
- terraform/modules/azure/aks/vars.tf
- terraform/modules/azure/data-explorer/main.tf
- terraform/modules/azure/data-explorer/vars.tf
- terraform/modules/azure/event-grid/main.tf
- terraform/modules/azure/event-grid/vars.tf
- terraform/modules/azure/event-hub-namespace/main.tf
- terraform/modules/azure/event-hub-namespace/vars.tf
- terraform/modules/azure/key-vault/main.tf
- terraform/modules/azure/key-vault/vars.tf
- terraform/modules/azure/managed_identities/main.tf
- terraform/modules/azure/managed_identities/vars.tf
- terraform/modules/azure/monitor-stack/main.tf
- terraform/modules/azure/monitor-stack/vars.tf
- terraform/modules/azure/postgres-flex-server/main.tf
- terraform/modules/azure/postgres-flex-server/vars.tf
- terraform/modules/azure/service-bus/main.tf
- terraform/modules/azure/service-bus/vars.tf
- terraform/modules/azure/storage-account/main.tf
- terraform/modules/azure/storage-account/vars.tf
We have reached some (Azure) resource quotas. This PR split the resource group location and the resource location to move AKS to NE
Related to #
> Move some resources to NE

- terraform/main.tf
> Move resources

- terraform/main.tf
- terraform/modules/azure/registry/main.tf
- terraform/modules/azure/registry/vars.tf
> feat: Add ACR proxy

- terraform/modules/azure/aks/main.tf
> feat: Remove AAD PodIdentity resources

- terraform/modules/azure/registry/main.tf
> fix: Add credentials to the cache

- terraform/main.tf
- terraform/modules/azure/aks/main.tf
- terraform/modules/azure/aks/vars.tf
- terraform/modules/azure/registry/outputs.tf
> Deploy tugger to replace images

- terraform/modules/azure/aks/main.tf
> use spegel

- terraform/modules/azure/registry/main.tf
> use de system permission

- terraform/modules/azure/registry/main.tf
> Use the System permission

- terraform/modules/azure/aks/main.tf
- terraform/terraform.tf
> Change kubectl provider

- terraform/modules/azure/aks/main.tf
> Disable config file

- terraform/modules/azure/registry/main.tf
> chore: Add purge task for the ACR

- terraform/main.tf
- terraform/modules/azure/app-registration/main.tf
- terraform/modules/azure/data-explorer/main.tf
- terraform/modules/azure/sql-server/main.tf
- terraform/modules/azure/sql-server/outputs.tf
- terraform/modules/azure/sql-server/vars.tf
- terraform/terraform.tf
> add sql server

- terraform/modules/azure/sql-server/main.tf
> fix: Add firewall rules to sql server

- terraform/main.tf
> bump k8s to 1.31

- terraform/main.tf
> Bump k8s to 1.32
